- 2014-12-29-the-death-of-cocoa.md
AppKit was the thing removed from Cocoa; UIKit was added in Cocoa Touch. I think it is more correct to say "Cocoa Touch is basically just Cocoa with UIKit substituted for AppKit".
> Substituted UIKit for AppKit

- 2014-09-15-image-resizing.md
Added UIGraphicsEndImageContext() function call to UIKit resizing example.
Documentation says:
> When you are done modifying the context, you must call the UIGraphicsEndImageContext function to clean up the bitmap drawing environment and remove the graphics context from the top of the context stack. 
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/#//apple_ref/c/func/UIGraphicsBeginImageContextWithOptions
> Add UIGraphicsEndImageContext()

- 2015-01-19-javascriptcore.md
And have a look how "{{getFullName}}, born {{birthYear}}" is displayed in github preview and on nshipster.com
That's because of different markdown flavours I think.
> Two small fixes.

- 2015-01-26-swift-objc-runtime.md
- Fixed singular/plural disagreement in "their Objective-C brethren, *the category*"
- Added an article: "you can't add a property to an existing class via *an* extension."
> Minor grammatical fixes

- 2014-11-10-core-location-in-ios-8.md
Changed the word 'has' to 'as' in the opening sentence and in the article excerpt.
> Corrected typo in Core Location article

- 2013-06-17-object-subscripting.md
- 2013-08-19-nshashtable-and-nsmaptable.md
I expect these changes need editing for consistent style and tone, but the existing articles are incorrect. Clang might have changed since the original articles were written.
Indexed subscripts may be of any integral type; the `NSUInteger` requirement is imposed by `NSArray`, not the compiler. Similarly, keyed subscripts may be of any Objective-C object pointer type, and `NSCopying` is only required by `NSDictionary` to match its existing API and provide compiler warnings when using subscripting.
For example, you could implement
- (NSData *)objectForKeyedSubscript:(NSURL *)key
to get type checking on the parameter and return types when using
NSData *fileData = myObject[myURL]
> Objective-C object subscripting corrections

- 2013-05-20-core-data-libraries-and-utilities.md
Fixes a typo in [Core Data Libraries & Utilities](http://nshipster.com/core-data-libraries-and-utilities/) - singular form.
> "Core Data Libraries & Utilities" typo

- 2014-11-10-core-location-in-ios-8.md
Fixes some typos in [Core Location in i​OS 8](http://nshipster.com/core-location-in-ios-8/) - missing verbs, particles, etc.
> "Core Location in i​OS 8" typos

- 2013-07-22-uimenucontroller.md
Since `-handleLongPressGesture:` is called each time the gesture recognizer's `state` changes, the `UIMenuController` ends up being presented multiple times. The result of presenting the menu controller multiple times is simply a visual glitch, so not a huge deal, but this change fixes it.
Also, I'm sorry if I guessed wrong on tabs vs. spaces. It seems like both were being used, so I guessed spaces.
> Fix presenting UIMenuController multiple times

- 2015-01-19-javascriptcore.md
Compile error if you use "class func" instead of "static func" in a protocols.
> Use static keyword instead of class for protocols

- 2015-06-22-ios9.md
Just translating words isn't enough. The resulting strings are still not correctly localized, but that's a problem with `setLocalizedDateFormatFromTemplate` itself.
Correct would be `23. Juni 2015, 16:56`, but that would require changing the template from `yyyyMMMMddhhmm` to `yyyyMMMMddHHmm`.
> Fixed example for localization

- 2013-08-19-nshashtable-and-nsmaptable.md
- 2014-03-31-avspeechsynthesizer.md
- 2014-11-03-uisplitviewcontroller.md
Added Objective-C for UISplitViewController, translated NSHashTable & NSMapTable to Swift, and updated AVSpeechSynthesizer. All audited for Swift 2.
I think I might have gotten my tabs to behave this time.
> Updates to UISplitViewController / NSHashTable & NSMapTable / AVSpeechSynthesizer

- 2012-07-31-nsdatecomponents.md
- 2012-11-26-nsorderedset.md
- 2013-07-15-nspredicate.md
- 2014-01-13-nsrange.md
- 2014-07-14-nsoperation.md
- 2014-09-16-phimagemanager.md
- 2015-01-26-swift-objc-runtime.md
- NSOrderedSet
- Swift 2 check, and removed a few unneeded explicit types.
- NSOperation
- Swift 2
- PHImageManager
- Swift 2 and added Objective-C
- NSRange 
- Added Swift translations. I translated this one-to-one with the Objective-C version, explicitly typing variables as NSString, NSArray, etc as needed to keep everything working on NSRanges instead of trying to use Swift's native Range. It felt kind of wrong, but a substantial overhaul of the article would be required to properly accommodate for Swift's Range (I think). Perhaps it deserves its own article.
- I also kept the usage of global functions like NSMakeRange instead of converting them to use the appropriate struct initializers and instance methods for things like unions. Not sure which of the two is considered "better" …
> Updates for NSOrderedSet, NSOperation, PHImageManager, NSRange, NSDateComponents, NSPredicate and Swift & the Objective-C Runtime

- 2013-09-09-network-link-conditioner.md
developer.apple.com's search no longer returns a search result for "Network Link Conditioner".  :( But it does for Hardware IO Tools for Xcode!
> Update search term

- 2013-10-14-nserror.md
The first change is to check the result value before checking the error, as we would when calling an API that returns a value and an error in a trailing (NSError **) parameter.
The second change is to show how to wrap an underlying NSError in a NSError with a custom domain and code.
> Improvements for Cocoa NSError conventions

- 2014-11-10-core-location-in-ios-8.md
Using `.Authorized` now gives warnings about `kCLAuthorizationStatusAuthorized` being deprecated.
> Update `.Authorized` to `.AuthorizedAlways`

- 2014-09-22-swift-comparison-protocols.md
Fix `CSSSelector.Specificity` comparison pointed out here: https://github.com/NSHipster/articles/commit/e4b977b30adc276ace718fa686e460a1a71d8d77#diff-6d92d5b6dd1d07f4ac6786ddc4e2c49cR167
> Update 2014-09-22-swift-comparison-protocols.md - specificity comparison condition fix

- 2014-08-11-swift-operators.md
I tried various combinaisons of operators, and only the ones who contain the /, =, -, +, !, *, %, <, >, &, |, ^, or ~ and Math Symbols character set works.
Ex: =2√ or =2√ does not work but =√ works.
> Custom operators in swift cannot contain any character

- 2013-06-24-uuid-udid-unique-identifier.md
Hay, I made a small change about NSUUID article.
I just changed the Swift example code to use designated initialiser rather class method `UUID()` because the class method support Objective-C only.
Please have a look my changes and let me know if you got any concerns.
Thanks,
> Change Swift example to create UUID

- 2014-07-21-xctestcase.md
There's an open issue regarding how `measureBlock` repeats tests. I added some information based on Apple's documentation, including that the baselines are per-device.
> #377: clarify how measureBlock works

- 2014-08-11-swift-operators.md
Updating the Operators post to reflect deprecations from [SE-0004](https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md) :smile:
> Remove references to ++ and --

- 2013-07-08-nsexpression.md
This SO article explains the issue:
http://stackoverflow.com/questions/31905752/random-and-random-function-for-nsexpressions-initforfunctionarguments/36331152#36331152
The article mentions the use of `random:` which doesn't exist. It is instead `randomn:`. The original article also incorrectly describes the use and result of `random:` which has also been updated.
It also appears as though the headers in NSExpression have been updated since this article to clearly show all valid functions. Here if someone wants to add them:
```
// Predefined functions are:
// name              parameter array contents				returns
//-------------------------------------------------------------------------------------------------------------------------------------
// sum:              NSExpression instances …
```
> Fix a reference to an NSExpression function that doesn't exist

- 2016-04-25-uitextchecker.md
Use `NSRange.init(_ x: Range<Int>)` instead of NSMakeRange. It's Swiftier.
> Replace NSMakeRange in Swift

- 2014-11-10-core-location-in-ios-8.md
As far as I know, the only changes here are that the instances don't need to be unwrapped anymore
> Update Core Location to Swift 2

- 2015-06-29-cloudkit.md
Since CloudKit does not allow "CONTAINS" to be used for string fields, only for collections.
> CloudKit: Update CONTAINS to be BEGINSWITH instead

- 2015-05-05-swift-documentation.md
Note that since Xcode 8 headerdoc has been retired in favour of [Swift markup](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/).
> update link to headerdoc user guide

- 2013-12-09-multipeer-connectivity.md
- 2014-07-14-nsoperation.md
I've updated sample code to Swift 3.0.
However, I left classes names (i.e. `NSBlockOperation`) in the article as is, since it wouldn't make lot of sense with the Objective-C sample code.
Also, I fixed a deadlink to make it point to the legacy `AFURLConnectionOperation.h` file which was still present in AFNetworking 2.x. (Removed in AFNetworking 3.0, hence the deadlink)
> Update 2014-07-14 NSOperation to Swift 3.0 syntax, and fix a deadlink, Convert 2013-12-09 MultipeerConnectivity to Swift 3.0

- 2013-10-07-key-value-observing.md
Properties that include `getter` overrides cannot use the `NSStringFromSelector(...)` method for generating clever key paths.
> Add custom getter gotcha to KVO article

- 2018-08-13-hashable.md
Fixes the comment for the initial collision example. 💥🚗
> Fix Hashable code example comment

- 2018-08-13-hashable.md
This also fixes one other error (they/we).
> Hashable/Hasher: Add a few missing words

- 2015-10-05-guard-and-defer.md
This PR fixes a small compiler error in the "Guarding Against Excessive Indentation and Errors" section.
The "before" code sample fails to compile because the expression `try Data(contentsOfUrl: url)` does not produce an Optional result. I updated it to match the "after" code sample, which uses `try?` instead (see line 177).
> Fix small error in "excessive indentation" code sample

- 2018-10-22-swiftsyntax.md
Found a small typo while reading the article.
> Fix typo: SwiftSynax -> SwiftSyntax

- 2013-07-15-nspredicate.md
It was a crash because you have to mark members of the class to be key/value complaint.
> Fixed crash in swift 4.2 with NSPredicate, and renamed a filter method to the new name

- 2019-02-11-swift-regular-expressions.md
This example only makes sense if “single-player” is supposed to be “multiplayer”.
> Correct typo in named capture groups section

- 2019-02-11-swift-regular-expressions.md
The period (full stop, dot) is a special symbol in regular expressions that matches any character, excluding newline. ([Unless the *s* flag is set.](https://developer.apple.com/documentation/foundation/nsregularexpression#1965592))
To match a literal period, the symbol must be escaped.
> Escape period (.) in regular expressions

- 2019-02-11-swift-regular-expressions.md
The "Matching Multi-Line Patterns with Named Capture Groups" example has a minor bug that breaks the match.  Specifically, the multiple spaces after "Dining Room" are not matched.
Proposed fix is to only have one space character in the "suggestion" string.
> Bug in "Named Capture Groups" example

- 2019-03-18-swift-foundation-error-protocols.md
Use `NSLocalizedRecoveryOptionsErrorKey` instead of repeating `NSRecoveryAttempterErrorKey`.
> Use correct key name

- 2019-04-22-cggeometry.md
The order of the elements in the SVG are CGFloat, CGPoint, CGVector, CGSize, CGRect. This makes the order of the description list match that.
> Order descriptions to match order of SVG graphic

- 2014-02-10-associated-objects.md
It's being interpreted as text-in-need-of-escaping where it is.
Before:
After:
fixes #621
> Moves </blockquote> to new line in “Associated Objects”

- 2019-06-24-propertywrapper.md
Mostly deleting vestigial words. The only additions are a comma on 135 and changing "only yet" to "only begun" on 934 because "yet" was used immediately on next line.
> Tiny corrections on Property Wrappers

- 2019-05-20-swift-format.md
When checking out the `swift-format` tool, I'm fairly certain that the default branch was `contributing`. Tripped me up for a sec, since I didn't think that I was on the incorrect branch until I ran `swift build` and it complained that nothing was there :)
> Adding checkout line for `swift-format`

- 2014-10-28-cmdevicemotion.md
1) `isDeviceMotionActive`->`isDeviceMotionAvailable` This is a typo I think. Compare with line 163 where `manager.isAccelerometerAvailable` is checked. Makes no sense to check if it is active before starting. Makes more sense to check if its available. 
2) 
`startDeviceMotionUpdates` takes `OperationQueue` not a `DispatchQueue`. Jumping to definition we see:
```
open func startDeviceMotionUpdates(to queue: OperationQueue, withHandler handler: @escaping CMDeviceMotionHandler)
```
That said, I still haven't been able to view these demos; these were just the changes needed to get it to compile and get to `startDeviceMotionUpdates`. For some reason the closure is still not running for me.
> Minor fixes

- 2019-09-23-ios-13.md
"Pattern matching in a condition requires the 'case' keyword"
> add "case" to fix compilation error

- 2019-11-19-keyvaluepairs.md
> Small typo to key value pairs

- 2019-09-23-ios-13.md
as of iOS 13.2 The supportsOnDeviceRecognition property now returns the correct value. (47822242)
> updated release notes for supportsOnDeviceRecognition

- 2014-05-19-benchmarking.md
I am actually not sure what was meant. monotonic? or nonatomic?
> Fixes typo in 2014-05-19-benchmarking.md

- 2012-07-31-datecomponents.md
Despite only seconds being fixed, I still believe this is true. :-) 
Also matches the previous declaration `var tomorrow: Date?`
> Next .second .hour with .forward is usually tomorrow

- 2019-10-14-swiftui-previews.md
This PR fixes a small typo in what is a quality & incredibly helpful article - because there is currently no such thing as an "iPad 11 Pro Max", the device shown in the preview pane is another iPhone SE.
> Correct iPad 11 Pro Max to iPhone

- 2020-02-12-callable.md
Just fixes a small typo, changing the word does to dose.
> Fix a Small Typo - does → dose

- 2019-09-02-dark-mode.md
without the explicit parentheses, only storyboard files
are processed. with the explicit parentheses, xibs are processed as well 😎
> adding explicit parens around find name arguments

- 2012-09-03-locale.md
DDM was the currency code of https://en.wikipedia.org/wiki/East_German_mark - so updating the meta-information would also be okay, but I suspect a lot more people know about Deutsche Mark.
> Changed currency code for "Deutsche Mark" to DEM

- 2020-01-06-at-compiler-directives.md
Although it implies unsafe_unretained, it is still prominent in the documentation
> Add common assign attribute to properties list

- 2012-09-17-characterset.md
Czech isn't one of the languages that would consider `dž` a single letter. 
The only example of that in Czech would be `ch`.
> Update 2012-09-17-characterset.md - Fix language info

- 2020-04-13-contact-tracing.md
Hello,
PR fixes small typo on [Contact Tracing](https://nshipster.com/contact-tracing/) article.
> fix: contact-tracing-en typo

- 2019-07-15-formatter.md
The article was rendering as an opening single quote, not an apostrophe (or closing single quote).
> Fix Apostrophe

- 2018-11-19-vscode.md
The extension in the article is unpublished as mentioned below:
> This extension is now unpublished from Marketplace. You can choose to uninstall it.
So update to use another extension https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swiftlint
> Update the swiftlint extension for 2018-11-19-vscode.md 

- 2019-12-10-available.md
In a declaration like `@available(macOS 10.15, *)`, the `*` indicates that that the API is _available_ on all other platforms. If you want to indicate that an API is unavailable on a particular platform, you would need to add a separate `@available` attribute for that platform.
(See https://docs.swift.org/swift-book/ReferenceManual/Attributes.html)
> Correctly define @available(*)

- 2019-07-01-uistackview.md
I *assume* that "starting with" was meant to be written here, but I'm not entirely sure.
Thanks for the informative and helpful article nonetheless 😊
> Fix typo in UIStackView article

- 2014-10-17-inter-process-communication.md
The name passed to `CFMessagePortCreateRemote` has to be the same name used when the port was created via `CFMessagePortCreateLocal` in the other process. This is a key part in how they figure out how to talk to each other. Otherwise `CFMessagePortCreateRemote` always returns `NULL`/`nil` since a port with the name given to it doesn't exist on the system. The example code might have tried to distinguish between the client and server by using different strings, but this causes the remote port creation to fail.
> In IPC article, use same string for port names in client and server

- 2018-12-03-homebrew.md
Given a custom prefix, the install command would not create the necessary folders and end up renaming the binary to "bin" when moving it to the destination folder.
So brew would create a binary "/usr/local/Cellar/swift-syntax-highlight/0.1.0/bin" and then fail to symlink it.
> Fix binary being renamed to bin

- 2013-02-11-nsurlcache.md
The link to the gist (probably demonstrating this was not implemented?!) was dead, so I replaced it with the iOS 13 release notes, which states that it's implemented there - seems fairly authoritative - and dropped the link to the open radar.
Also while I was at it, I changed the spelling to lowercase first, to match the latest Swift conventions.
> [NSURLCache] Reflect that `.reloadIgnoringLocalCacheData` and `.reloadRevalidatingCacheData` are implemented

- 2018-11-26-simctl.md
I may be missing something, but I'm pretty sure the only way to use `pbcopy` is to pipe something into it, e.g. `cat ~/Desktop/file.txt | pbcopy`. Running the command in the article, `pbcopy ~/Desktop/file.txt`, waits for more input on the command line.
Side note: I'm also confused by the definitions of `pbcopy` and `pbpaste` in the article. The article says "`pbpaste` takes the pasteboard contents of the Simulator and copies them to the desktop's main pasteboard". However, the example clearly does the opposite: takes the contents of the desktop's main pasteboard and copies it to the Simulator's pasteboard. The example is correct; running the command in the article after the corrected `pbcopy` command works as the article intends. However, your description also matches Apple's …
> Fix pbcopy example in simctl article

- 2018-07-09-swift-gyb.md
They renamed the master branch to main.
> [GYB Article] Fixed links to Swift repository

- 2019-05-20-swift-format.md
The installation instructions provided was vastly outdated
> Update installation instructions for swift-format

- 2013-06-02-nsdatadetector.md
Fix an extremely minor but confusing typo.
18000sec / 60sec-per-min / 60min-per-hour = 5 hours
> nsdatadetector - Specify the correct duration

- 2018-12-03-homebrew.md
Ruby 1.9's simpler non-hashrocket syntax is now preferred by Homebrew for submitted formulae.
I looked for other Ruby hashes and found some in the CocoaPods articles (`Stewardship`, `CocoaPods`) , but I haven't used CocoaPods in a few years so I'm not sure what the convention is there.
> Homebrew Formulas - Ruby Hashrocket Upgrade

- 2019-11-12-secrets.md
The second argument in the `decode` function is named `cipher`, not `salt`.
> Use correct argument name in sample code
