2014-11-03-uisplitviewcontroller.md
Minor grammar, capitalization, and formatting fixes.
=> UISplitViewController fixes

2013-05-20-core-data-libraries-and-utilities.md
Removed an extra 'is' in the sentence beginning "This is list is by no means comprehensive..."
=> Small typo in Core Data article.

2015-01-19-javascriptcore.md
I will delete the eng version after review done. @croath @rickytan
=> Translate 2015-01-19-javascriptcore

2015-01-19-javascriptcore.md
Perhaps my shortest PR ever? This might not be the desired change, but the current version doesn't scan correctly.
Keep on keeping on etcetera. cheers!
=> added missing "to"

2014-12-15-nsundomanager.md, 2015-01-05-changing-of-the-guard.md
- 2015-01-05-changing-of-the-guard.md
- 2014-12-15-nsundomanager.md
=> Zh-hans nsundomanager

2014-11-17-uiprintinteractioncontroller.md, 2015-02-02-ibinspectable-ibdesignable.md
@croath , please review. Thanks.
=> translate  2014-11-17-uiprintinteractioncontroller done

2015-02-02-ibinspectable-ibdesignable.md
this is even worse than the last one.
cheers!
=> "an'd" an "a"

2015-03-02-nsscanner.md
So the typo is clear, but I'm not sure about what you intended for the missing section. I offered my 'best guess', but I'm not a particularly good technical writer, I'm coming to realize. So: I imagine you had something pithier + clearer in mind, there, and I'm happy to mostly just highlight that it didn't quite make it in.
:v: :sunglasses: :v:
=> fixed a typo, and completed a missing paragraph.

2014-04-21-uiactivityviewcontroller.md
There is no UIActivityProvider class but UIActivityItemProvider
=> Fixing class name in UIActivityViewController article

2013-10-07-key-value-observing.md
translate 2013-10-07-key-value-observing article, please review!
=> translate 2013-10-07-key-value-observing

2012-10-08-at-compiler-directives.md, 2013-04-29-mklocalsearch.md
=> translate 2013-04-29-mklocalsearch.md

2013-10-07-key-value-observing.md
修改了代码块的格式问题，并且文章最开头忘了写 ---，已修正。
=> fix codeblock format

2013-09-23-ios7.md
First time contributing to NSHipster articles. Please let me know if I need to change anything.
=> Added Swift translations to 2013-09-23-ios7.md

2015-05-11-xcplayground.md
asciiwwdc needs to be .com, not .org
=> Fixed broken link

2013-05-27-unit-testing.md
translate 2013-05-27-unit-testing to zh-Hans
=> translate 2013-05-27-unit-testing to zh-Hans

2014-03-24-nsurl.md
modify table to image;
add spaces between English and Chinese;
link to Chinese version of Wiki;
=> hotfix nsurl

2014-08-11-swift-operators.md
swift operations tranlate to zh
=> swift operations tranlate to zh

2013-03-25-search-kit.md
please review @croath @aprilnov :joy:
=> translate Search kit

2013-03-18-c-storage-classes.md
=> translate 2013-03-18-c-storage-classes.md

2015-10-05-guard-and-defer.md
=> Minor change

2014-10-06-swift-system-version-checking.md
@rickytan @croath , plz review, thanks~
=> translate 2014-10-06-swift-system-version-checking.md

2015-10-05-guard-and-defer.md
Please review @rickytan . Thanks!
=> `guard and defer` article translation.

2015-05-11-xcplayground.md
Playground文章的翻译，里面有的名词不太确定是不是需要翻成中文，或者是否准确，敬请指正。
=> translated-2015-05-11-xcplayground-first_commit

2014-03-03-nstemporarydirectory.md
Quick typo fix in `nstemporarydirectory.md`.
=> nstemporarydirectory.md - Quick typo fix.

2012-07-14-nscache.md, 2012-07-24-nssortdescriptor.md, 2014-10-28-cmdevicemotion.md
This PR updates:
- NSCache (no changes necessary, but now tagged for 2.2)
- NSSortDescriptor
- CMDeviceMotion
=> Article updates

2012-11-19-ns_enum-ns_options.md
=> NS_ENUM & NS_OPTIONS - Typo

2016-04-25-uitextchecker.md
=> Fix a typo: Update 2016-04-25-uitextchecker.md

2012-10-29-uilocalizedindexedcollation.md
`which are can be read from the sectionIndexTitles property.` --> `which can be read from the sectionIndexTitles property.`
=> Fix grammatical error

2013-01-07-nil.md
https://gist.github.com/4469665 returns 404
=> Broken Link

2014-09-22-swift-comparison-protocols.md
=> Swift Comparison Protocols - Typo Fix

2013-11-18-nsfilemanager.md
can this be merged? any Chinese here?
=> fix typo 修改翻译错误

2013-10-21-launch-arguments-and-environment-variables.md
2013-10-21-launch-arguments-and-environment-variables.md
=> translate  2013-10-21

2013-09-09-network-link-conditioner.md
Updated Network link conditioner links for Xcode 8, and renamed the old one.
=> Download links update

2014-10-28-cmdevicemotion.md
🎄 🎄 🎄 
Swift 3.0 updates for *CMDeviceMotion*: http://nshipster.com/cmdevicemotion/
=> update 2014-10-28-cmdevicemotion for Swift 3.0  🎄  🎄  🎄 

2015-01-26-swift-objc-runtime.md
This just clarifies that only computed properties can be added via extensions in both languages.
=> Clarifying allowed properties in extensions

2013-07-01-enumerators.md
=> translate 2013-07-01-enumerators.md

2013-01-07-nil.md
=> formatting fix

2018-08-13-hashable.md
=> Hashable typo fixes

2015-10-05-guard-and-defer.md
=> Fix typo “works” not “words

2015-03-02-nsscanner.md
=> Update NSScanner to Swift 4.2

2019-01-07-import.md
=> fix 2019-01-07-import.md typo

2019-02-18-swift-api-pollution.md
=> Fixed minor typo

2019-01-21-textoutputstream.md
probably a typo.
Thanks for the articles..
=> typo? Update 2019-01-21-textoutputstream.md

2019-03-18-swift-foundation-error-protocols.md
I'm not sure about the grammar on this change, so please reject if I'm wrong. 😊
=> Replace 'than' with 'then'

2019-04-08-uitableviewheaderfooterview.md
=> Fix sentence flows

2019-03-18-swift-foundation-error-protocols.md
Fixed the style and the wrong argument.
=> Fix sample code for UIAlertController’s extension

2019-03-18-swift-foundation-error-protocols.md
=> Remove duplicate "when"

2019-04-29-optional-throws-result-async-await.md
Fixes compile errors in one of snippets of 2019-04-29-optional-throws-result-async-await.md
=> Fixes compile errors in snippet

2019-09-02-dark-mode.md
I think you meant “darker color palettes”, (or possibly, “a darker color palette”)
=> Fix small typo

2019-07-01-uistackview.md
Thanks for all those great articles! 🎉 During today's revisit of the UIStackView article I discovered a small typo that will be fixed with this PR.
=> Fix small typo in UIStackView article

2019-09-02-dark-mode.md
=> Fix colorLiteral sed one-liner (dark-mode.md)

2019-11-19-keyvaluepairs.md
=> Fixed a typo with the Japanese romaji for Rock-Paper-Scissors

2020-01-29-rawrepresentable.md
https://twitter.com/_lanceparker/status/1222577567695163392
=> String backed enums have raw values that match the case name by default

2020-03-26-swift-log.md
Love your articles! Keep up the good work. 👍
=> Typo and syntax fix.

2019-07-15-formatter.md
Reverts NSHipster/articles#732
=> Revert "Add missing decimal point in number formatter example"

2014-02-17-method-swizzling.md
I messed it up when I changed this and it has been driving me mad ever since
=> Fix typo in method swizzling example
